### ISSUE TITLE
clearing and system commands suggestion 

### ISSUE THREAD

**Issue by TotallyNotAHaxxer** [americo/sqlifinder#3]
i have something i use alot in my own scripts to save the time writing os.system commands so, here it is 
change this
```python
def clear():
    if 'linux' in sys.platform:
        os.system('clear')
    elif 'darwin' in sys.platform:
        os.system('clear')
    else:
        os.system('cls')
```
to this 

```python

def clear():
    print("\x1b[H\x1b[2J\x1b[3J") 
```
this will clear every terminal, on any system no matter if its UNIX, Linux, Windows, MACOS, Iphone, Android, whatever. helps alot dont it? ;o

**Comment by americo** [comment]
Thank you!
I want to recode this tool, i will implement this.
